version: '3.8'

services:
  app:
    container_name: tdt-scan-app
    image: tdt-sql-scan:staging
    ports:
      - "8080:8080"
    environment:
      # JVM Options
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}

      # Datasource
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVERCLASSNAME=${SPRING_DATASOURCE_DRIVERCLASSNAME}

      # Mail Server
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_FROM=${SPRING_MAIL_FROM}

      # Third-Party Services
      - TINYMCE_API_KEY=${TINYMCE_API_KEY}
